# Generated by Django 5.1.7 on 2025-03-10 05:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_district_state_bloodbank_district_state_bloodstock'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bloodbank',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='bloodstock',
            options={'ordering': ['blood_bank', 'blood_group', 'component']},
        ),
        migrations.AlterModelOptions(
            name='district',
            options={'ordering': ['state', 'name']},
        ),
        migrations.AlterModelOptions(
            name='state',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='bloodstock',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bloodbank',
            name='contact_number',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='bloodbank',
            name='license_number',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message="License number must be in format: 'XX999999' (2 uppercase letters followed by 6 digits)", regex='^[A-Z]{2}\\d{6}$')]),
        ),
        migrations.AlterField(
            model_name='bloodstock',
            name='units_available',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, message='Units cannot be negative'), django.core.validators.MaxValueValidator(1000, message='Maximum 1000 units allowed')]),
        ),
        migrations.AlterField(
            model_name='state',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='district',
            unique_together={('state', 'name')},
        ),
        migrations.AddIndex(
            model_name='bloodbank',
            index=models.Index(fields=['license_number'], name='accounts_bl_license_bacbff_idx'),
        ),
        migrations.AddIndex(
            model_name='bloodbank',
            index=models.Index(fields=['district', 'is_active'], name='accounts_bl_distric_cd89e8_idx'),
        ),
        migrations.AddIndex(
            model_name='bloodstock',
            index=models.Index(fields=['blood_group', 'component'], name='accounts_bl_blood_g_a1233c_idx'),
        ),
        migrations.AddIndex(
            model_name='bloodstock',
            index=models.Index(fields=['blood_bank', 'units_available'], name='accounts_bl_blood_b_c04d1c_idx'),
        ),
    ]
