# Generated by Django 5.1.7 on 2025-03-14 18:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_bloodbank_options_alter_bloodstock_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodCamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.TextField(help_text='Detailed address of the camp')),
                ('camp_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('contact_person', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('expected_donors', models.PositiveIntegerField(default=50, validators=[django.core.validators.MinValueValidator(10, message='Expected donors should be at least 10'), django.core.validators.MaxValueValidator(1000, message='Expected donors cannot exceed 1000')])),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, help_text='Additional details about the camp')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blood_bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blood_camps', to='accounts.bloodbank')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blood_camps', to='accounts.district')),
            ],
            options={
                'ordering': ['camp_date', 'start_time'],
                'indexes': [models.Index(fields=['camp_date'], name='accounts_bl_camp_da_bf005e_idx'), models.Index(fields=['district', 'is_active'], name='accounts_bl_distric_c2e7f0_idx'), models.Index(fields=['blood_bank', 'is_active'], name='accounts_bl_blood_b_549f8c_idx')],
            },
        ),
    ]
