# Generated by Django 5.0.4 on 2025-04-22 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_blooddonationcamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='donation_status',
            field=models.CharField(choices=[('NOT_DONATED', 'Not Donated'), ('DONATED', 'Donated')], default='NOT_DONATED', max_length=15),
        ),
    ]
